services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: dev-pm2-dashboard-backend

    restart: unless-stopped

    env_file:
      - ./backend/.env

    ports:
      - "172.16.16.43:8002:8002"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - /home/jenkins/.ssh:/home/jenkins/.ssh:ro
      - /var/www/fullstack:/var/www/fullstack

    networks:
      - pm2-dashboard


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: dev-pm2-dashboard-frontend

    restart: unless-stopped

    ports:
      - "172.16.16.43:3002:3002"

    networks:
      - pm2-dashboard


networks:
  pm2-dashboard:
    driver: bridge
